version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/ufl-test
    steps:
      - checkout
      - run:
          name: Install dependencies  # Install with sudo as tests not run as superuser in circleci/python
          command: sudo pip install flake8 numpy pytest coverage coveralls --upgrade
      - run:
          name: Install UFL
          command: pip install --user .
      - run:
          name: Run flake8 tests
          command: python -m flake8 .
      - run:
          name: Run unit tests
          command: |
                coverage run --source ufl -m pytest --junitxml=test-output test/
                coveralls
      - store_test_results:
          path: test-output/
